# Generated by Django 5.0.6 on 2024-07-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mygrocerylist.list'),
        ),
        migrations.DeleteModel(
            name='ListManager',
        ),
    ]
