# Generated by Django 5.0.6 on 2024-07-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrocerylist', '0002_product_list_delete_listmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygrocerylist.list'),
        ),
    ]
