# Generated by Django 5.0.6 on 2024-07-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrocerylist', '0003_alter_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(default='my new list', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ammount',
            field=models.IntegerField(default=1),
        ),
    ]
