# Generated by Django 5.0.6 on 2024-07-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygrocerylist', '0005_user_list_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ammount',
            new_name='amount',
        ),
    ]
